### PR TITLE
Add support for NVDEC-enabled VAAPI driver 

### PR DESCRIPTION
**Pull request by Mazotis**
And added requirements: bumped nv headers for recent drivers, updated README and symlinked VDPAU if it's not already installed.

### CODE REVIEW

**Comment by Mazotis** [comment]
Still experimental I guess, but I tested 4K output on Chrome and, although the terminal spits some errors, I did not notice any stuttering and there are no reported frame drops. Feel free to re-edit the readme or set it as an optional feature if required!

**Comment by marioroy** [comment]
Hi @Mazotis,

There are several things to address.

1. All the libs have been consistent and installed to /usr/local/lib. Add --libdir=lib option to meson setup.
2. For safety, not wanting to assume folks have Nvidia driver > 470.57. A check is needed to skip building if not > 470.57.
3. I'm trying to understand why adding a symbolic link to /usr/lib64.  Perhaps item 1 above makes it unnecessary as the instructions for Firefox mentions setting LD_LIBRARY_PATH to /usr/local/lib.

Version checking:

```bash
version=`/opt/nvidia/bin/nvidia-settings --version | grep version`
version=${version##* } # extract the version string from the line
version=`echo $version | cut -d. -f1-2` # want major and minor, not revision

# Exit silently if the the graphics driver is not > 470.57.
[[ $(bc -l <<< "${version} <= 470.57") -eq 1 ]] && exit 0
```

**Comment by marioroy** [comment]
In the event the build failed, not to make the symbolic link.  Check status. This includes the option `--libdir=lib` to setup.

```bash
if [[ -d ${name} ]]; then
    mkdir -p ${name}/build && cd ${name}/build
    LDFLAGS="-L/opt/nvidia/lib/" LIBRARY_PATH="/opt/nvidia/lib" PKG_CONFIG_PATH="/usr/local/lib/pkgconfig" \
    meson setup .. --prefix=/usr/local --libdir=lib && \
    ninja install
    if [[ $? -eq 0 && ! -f /usr/lib64/dri/nvidia-nvdec_drv_video.so ]]; then
        ln -s /usr/local/lib/dri/nvidia_drv_video.so /usr/lib64/dri/nvidia-nvdec_drv_video.so
    fi
fi
```

**Comment by Mazotis** [comment]
Sorry for this  - my bad. I had a self compiled app that didn't work after compiling vdpau. Thought it came from a clear bundle. The symlink is not required. I will make a cleaner request.

**Pull request closed without merging**
